FROM denissliva:php8.1-astaroth
#
# Further yourself
#

#RUN composer install --no-dev --classmap-authoritative

#
# Longpolling
# ENTRYPOINT ["php", "index.php"]
#

#
# Callback
# need web-server which will send requiest to index file
#

