FROM denissliva:php8.1-astaroth
#
# Further yourself
#

# RUN composer install --no-dev --classmap-authoritative

# Example
# Add pgsql

# RUN apk add postgresql-dev composer
# RUN docker-php-ext-install pdo_pgsql
#

#
# Longpolling

# ENTRYPOINT ["php", "index.php"]
#

#
# Callback
# need web-server which will send requiest to index file
#

