version: "3.3"

volumes:
  db_volume:

services:

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      TZ: "Europe/Moscow"

      POSTGRES_PASSWORD: "Ercdf6j72cUmYJfs4QNymkzQxtQvd2jcCjCzHdrkQK8KhEsteu8CYsewS9MvXXMADNK6eY4GXrYavyzKr5hned6RypWKq"
      POSTGRES_USER: "app"

    ports:
        - "5432:5432"
    volumes:
        - db_volume:/data/db

  app:
    restart: always
    container_name: app
    volumes:
      - ../:/app/
    working_dir: /app/
    build:
      context: ../
      dockerfile: docker/Dockerfile

    env_file:
      - ../.env
    environment:
      TZ: "Europe/Moscow"